# Generated by Django 4.0.4 on 2022-05-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='num_visit',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RecentView',
        ),
    ]
