# Generated by Django 4.0.3 on 2022-05-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_last_visit_product_num_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='firm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
