# Generated by Django 4.0.4 on 2022-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='firm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
